# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    # https://stackoverflow.com/questions/65863552/how-to-disable-cache-in-symfony-5-2
    cache:
        app: cache.adapter.null
        system: cache.adapter.null
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

# https://stackoverflow.com/questions/65863552/how-to-disable-cache-in-symfony-5-2
services:
    cache.adapter.null:
        class: Symfony\Component\Cache\Adapter\NullAdapter
        arguments: [~] # small trick to avoid arguments errors on compile-time.

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
