twig:
    default_path: '%kernel.project_dir%/templates'
    cache: false
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals: 
        ga_code: GAcode-123

when@test:
    twig:
        strict_variables: true
